### ISSUE TITLE
[Feature] Dict json format for paper_trade_account_balance and min_quote_order_amount

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2145]
**Feature Suggestion**
Currently `paper_trade_account_balance` and` min_quote_order_amount` store their data in a json list format, which, I think, is harder for users to manually update (than the dictionary format one). And from the data structure prospective, they should be dictionary (as you shouldn't have the same entry for the same token).  `balance_asset_limit` (implemented by @CrimsonJacket) uses the dictionary format and looks cleaner imo.

Example
```
paper_trade_account_balance:
- - USDT
  - 3000
- - ONE
  - 1000
- - BTC
  - 1
- - ETH
  - 10
balance_asset_limit:
  radar_relay:
  kraken:
    BTC: 0.2
  binance:
    LINK: 99
    BTC: 0.2
```

The above `paper_trade_account_balance` will then be
```
paper_trade_account_balance:
  USDT: 3000
  ONE: 1000
  BTC: 1
  ETH: 10
```
**Impact**
Changing the format is quite a simple task, but you might need to handle migration for users of the old format to the new one.
