### ISSUE TITLE
[BUG] Minimum quote order amount not working on some connectors

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2329]
**Describe the bug**

By default, we have a minimum order amount when prompted for the `order_amount` parameter. This is not working for some connectors. It only works in Bittrex, Coinbase Pro, KuCoin, and Liquid.

![image](https://user-images.githubusercontent.com/50150287/93163188-10844a80-f749-11ea-94ae-23b6e6751c7a.png)

**Steps to Reproduce**

1. Do not change the `min_quote_order_amount` in `conf_global.yml` file or leave them at default settings

```
min_quote_order_amount:

  BTC: 0.0011
  ETH: 0.05
  USD: 11
  BNB: 0.5
  USDT: 11
  USDC: 11
```

2. Run Hummingbot and `create` a pure market making config file on the following exchanges:
- Binance
- Crypto.com
- Eterbase
- Huobi
- Kraken
- Decentralized exchanges

**Environment**

Version: 0.31.0
Branch: Latest
Installation type: Source, Docker
Machine: PC, AWS Instance
OS: macOS, Linux, Windows
