### ISSUE TITLE
Arbitrage on same exchange never executes

### ISSUE THREAD

**Issue by austinbv** [CoinAlpha/hummingbot#3857]
When you set up an arbitrage where both legs are the same exchange, even with an extremely low minimum profit no orders are created and no errors are shown in logs.

**Comment by nikspz** [comment]
Hi @austinbv , Could you please share:
- your config and log file.
- your Machine type and installation type

**Comment by austinbv** [comment]
@nikspz thanks for the crazy fast reply

```yaml
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 5
strategy: arbitrage

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: coinbase_pro
secondary_market: coinbase_pro
primary_market_trading_pair: ETH-USDC
secondary_market_trading_pair: ETH-USD

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 0.00000001

# Whether to use rate oracle on unmatched trading pairs
# Set this to either True or False
use_oracle_conversion_rate: false

# The conversion rate for secondary base asset value to primary base asset value.
# e.g. if primary base asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_base_conversion_rate: 1.0

# The conversion rate for secondary quote asset value to primary quote asset value.
# e.g. if primary quote asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_quote_conversion_rate: 1.0

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters
```

My Machine type is OSX but I have tried on Linux and in docker as well

<img width="1440" alt="Screen Shot 2021-08-05 at 8 53 56 AM" src="https://user-images.githubusercontent.com/634699/128361940-adfc9b68-500e-48a2-b746-fabeba79bc9b.png">
