### ISSUE TITLE
`rate_limits_share_pct` doesn't seem to be working for dydx_perpetual

### ISSUE THREAD

**Issue by ryuheechul** [CoinAlpha/hummingbot#4366]
**Describe the bug**
- I have 4 bots running in same host via Docker and set `rate_limits_share_pct: 10.0`
- API requests to (api.dydx.exchange) constantly getting banned by cloudflare
- but I don't see any warning notifications about rates being limited.

References:
- https://docs.hummingbot.io/global-configs/rate-limits-share-pct/
- https://docs.hummingbot.io/exchanges/dydx-perpetual/

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set `rate_limits_share_pct: 10.0` in `conf_global.yml`
2. Run at least two bots (importing dydx_perpertual and starting) on the same host 

**Screenshots**
<img width="610" alt="Screenshot 2021-10-04 at 07 45 51" src="https://user-images.githubusercontent.com/2637709/135805616-deb703ee-2a3b-4628-90b8-53dad9269ad9.png">

**Release version**
0.44.0

**Attachments**
`rate_limits_share_pct: 10.0`

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Carl0423** [comment]
Hi @ryuheechul, for us to further investigate, can you please send us a copy of your config and log file? It'll also help us replicate the issue.

**Comment by ryuheechul** [comment]
@Carl0423 sure :)


<details><summary>Click to expand global config</summary>
<p>

```yaml
#################################
###   Global configurations   ###
#################################

# For more detailed information: https://docs.hummingbot.io
template_version: 24

# Exchange configs
bamboo_relay_use_coordinator: false
bamboo_relay_pre_emptive_soft_cancels: false

celo_address:
ethereum_wallet: xxx # obscured
ethereum_rpc_url: xxx # obscured
ethereum_rpc_ws_url: xxx # obscured
ethereum_chain_name: MAIN_NET
ethereum_token_list_url: https://wispy-bird-88a7.uniswap.workers.dev/?url=http://tokens.1inch.eth.link

# Kill switch
kill_switch_enabled: false
# The rate of performance at which you would want the bot to stop trading (-20 = 20%)
kill_switch_rate: -100.0

# What to auto-fill in the prompt after each import command (start/config)
autofill_import:

# DEX active order cancellation
0x_active_cancels: false

# Paper Trading
paper_trade_enabled: false
paper_trade_account_balance:
  BTC: 1
  USDT: 1000
  ONE: 1000
  USDQ: 1000
  TUSD: 1000
  ETH: 10
  WETH: 10
  USDC: 1000
  DAI: 1000

telegram_enabled: false
telegram_token:
telegram_chat_id:

# Error log sharing
send_error_logs: true

# Advanced configs: Do NOT touch unless you understand what you are changing
instance_id: xxx  # obscured
log_level: INFO
debug_console: false
strategy_report_interval: 900.0
logger_override_whitelist:
- hummingbot.strategy.arbitrage
- hummingbot.strategy.cross_exchange_market_making
- conf
key_file_path: conf/
log_file_path: logs/
on_chain_cancel_on_exit: false

# Minimum default order amount (in quote currency), this is used for when prompting a new order_amount.
min_quote_order_amount:
  BTC: 0.0011
  ETH: 0.05
  USD: 11
  BNB: 0.5
  USDT: 11
  USDC: 11
  BUSD: 11
  TUSD: 11
  TRY: 11

# Advanced database options, currently supports SQLAlchemy's included dialects
# Reference: https://docs.sqlalchemy.org/en/13/dialects/
db_engine: sqlite
db_host: xxx  # obscured
db_port: xxx  # obscured
db_username: xxx  # obscured
db_password: xxx  # obscured
db_name: xxx  # obscured

script_enabled: false
script_file_path:

# Balance Limit Configurations
# e.g. Setting USDT and BTC limits on Binance.
# balance_asset_limit:
#   binance:
#     BTC: 0.1
#     USDT: 1000
balance_asset_limit:
  binance:

# Fixed gas price (in Gwei) for Ethereum transactions
manual_gas_price: 50.0

# Gateway API Configurations
# default host to only use localhost
# Port need to match the final installation port for Gateway
gateway_api_host: localhost
gateway_api_port: '5000'

# Whether to enable aggregated order and trade data collection
heartbeat_enabled: true
# The frequency of sending the aggregated order and trade data (in minutes, e.g. enter 5 for once every 5 minutes)
heartbeat_interval_min: 15.0
# a list of binance markets (for trades/pnl reporting) separated by ',' e.g. RLC-USDT,RLC-BTC
binance_markets: HARD-USDT,HARD-BTC,XEM-ETH,XEM-BTC,ALGO-USDT,ALGO-BTC,COTI-BNB,COTI-USDT,COTI-BTC,MFT-BNB,MFT-ETH,MFT-USDT,RLC-ETH,RLC-BTC,RLC-USDT



# Command Shortcuts
# Define abbreviations for often used commands
# or batch grouped commands together
#
command_shortcuts:
- command: spreads
  help: Set bid and ask spread
  arguments: [Bid Spread, Ask Spread]
  output: [config bid_spread $1, config ask_spread $2]

# A source for rate oracle, currently binance or coingecko
rate_oracle_source: binance

# A universal token which to display tokens values in, e.g. USD,EUR,BTC
global_token: USD

# A symbol for the global token, e.g. $, €
global_token_symbol: $

# Percentage of API rate limits (on any exchange and any end point) allocated to this bot instance.
# Enter 50 to indicate 50%. E.g. if the API rate limit is 100 calls per second, and you allocate 50% to this setting,
# the bot will have a maximum (limit) of 50 calls per second
rate_limits_share_pct: 10.0

# network timeout when fetching minimum order amount in the `create` command
create_command_timeout: 10.0

# network timeout for other commands (i.e. import, connect, balance, history)
other_commands_timeout: 30.0
```

</p>
</details>

<details><summary>Click to expand perpetual mm strategy config</summary>
<p>

```yaml
########################################################
###       Perpetual market making strategy config         ###
########################################################

template_version: 5
strategy: perpetual_market_making

# derivative and token parameters.
derivative: dydx_perpetual

# Token trading pair for the exchange, e.g. BTC-USDT
market: AVAX-USD

# What leverage to used
leverage: 2

# Position mode to use, hedge mode or one-way position mode.
position_mode: One-way

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 0.2

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 0.3

# Minimum Spread
# How far away from the mid price to cancel active orders
minimum_spread: -100.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 500.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 0.0

# Size of your bid and ask order.
order_amount: 20

# Which position management feature to use. Trailing stop and take profit features are currently supported
position_management: Profit_taking

# long position take profit spread
long_profit_taking_spread: 0.0

# short position take profit spread
short_profit_taking_spread: 0.0

# Activation spread for trailing stop
ts_activation_spread: 0.0

# Callback rate for trailing stop
ts_callback_rate: 0.0

# Spread from position entry price to place a stop-loss order to close position
stop_loss_spread: 1.0

# OrderType to use for closing positions when using Trailing stop feature
close_position_order_type: LIMIT

# Price band ceiling.
price_ceiling: -1.0

# Price band floor.
price_floor: -1.0

# Whether to alternate between buys and sells (true/false).
ping_pong_enabled: false

# Number of levels of orders to place on each side of the order book.
order_levels: 1

# Increase or decrease size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top ask (for order optimization mode).
ask_order_optimization_depth: 0

# The depth in base asset amount to be used for finding top bid (for order optimization mode).
bid_order_optimization_depth: 0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# The price source (current_market/external_market/custom_api).
price_source: current_market

# The price type (mid_price/last_price/last_own_trade_price/best_bid/best_ask).
price_type: mid_price

# An external exchange name (for external exchange pricing source).
price_source_derivative:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for custom_api pricing source).
price_source_custom_api:

# An interval time in second to update the price from custom api (for custom_api pricing source).
custom_api_update_interval: 5.0

#Take order if they cross order book when external price source is enabled
take_if_crossed:

# Use user provided orders to directly override the orders placed by order_amount and order_level_parameter
# This is an advanced feature and user is expected to directly edit this field in config file
# Below is an sample input, the format is a dictionary, the key is user-defined order name, the value is a list which includes buy/sell, order spread, and order amount
# order_override:
#   order_1: [buy, 0.5, 100]
#   order_2: [buy, 0.75, 200]
#   order_3: [sell, 0.1, 500]
# Please make sure there is a space between : and [
order_override:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```
</p>
</details>

<details><summary>Click to expand the log file</summary>
<p>

```
<span>1015</span>
</h1>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 698cdb618d166577 &bull;</span>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2021-10-04 07:57:01 UTC</span>
<h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">You are being rate limited</h2>
</header>
<section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
<div id="what-happened-section" class="w-1/2 md:w-full">
<h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>
<p>The owner of this website (api.dydx.exchange) has banned you temporarily from accessing this website.</p>
</div>
</section>
<div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
<p class="text-13">
<span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">698cdb618d166577</strong></span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 167.99.199.235</span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
<script type="23d48e6524920478d89a9322-text/javascript">
  window._cf_translation = {};
  
  
</script>
<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="23d48e6524920478d89a9322-|49" defer=""></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"xxobscuredx","token":"xxobscuredx","version":"2021.9.0","si":100}'></script>
</body>
</html>
)
2021-10-04 07:57:01,093 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - WARNING - Could not fetch funding_rate for AVAX-USD. Check API key and network connection.
2021-10-04 07:57:01,239 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Issue with dydx API GET to v3/markets, response: 
2021-10-04 07:57:01,239 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | api.dydx.exchange used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />
<script defer src="https://api.radar.cloudflare.com/beacon.js"></script>
</head>
<body>
<div id="cf-wrapper">
<div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
<div id="cf-error-details" class="p-0">
<header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased">
<h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight">
<span data-translate="error">Error</span>
<span>1015</span>
</h1>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 698cdb629b0dbc06 &bull;</span>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2021-10-04 07:57:01 UTC</span>
<h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">You are being rate limited</h2>
</header>
<section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
<div id="what-happened-section" class="w-1/2 md:w-full">
<h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>
<p>The owner of this website (api.dydx.exchange) has banned you temporarily from accessing this website.</p>
</div>
</section>
<div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
<p class="text-13">
<span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">698cdb629b0dbc06</strong></span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 167.99.199.235</span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
<script type="text/javascript">
  window._cf_translation = {};
  
  
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"xxobscuredx","token":"xxobscuredx","version":"2021.9.0","si":100}'></script>
</body>
</html>

2021-10-04 07:57:01,241 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
2021-10-04 07:57:11,270 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Issue with dydx API GET to v3/markets, response: 
2021-10-04 07:57:11,271 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | api.dydx.exchange used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />
<script defer src="https://api.radar.cloudflare.com/beacon.js"></script>
</head>
<body>
<div id="cf-wrapper">
<div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
<div id="cf-error-details" class="p-0">
<header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased">
<h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight">
<span data-translate="error">Error</span>
<span>1015</span>
</h1>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 698cdba15a4e4268 &bull;</span>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2021-10-04 07:57:11 UTC</span>
<h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">You are being rate limited</h2>
</header>
<section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
<div id="what-happened-section" class="w-1/2 md:w-full">
<h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>
<p>The owner of this website (api.dydx.exchange) has banned you temporarily from accessing this website.</p>
</div>
</section>
<div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
<p class="text-13">
<span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">xxobscuredxx</strong></span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 167.99.199.235</span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
<script type="text/javascript">
  window._cf_translation = {};
  
  
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"698cdba15a4e4268","token":"xxobscuredx","version":"2021.9.0","si":100}'></script>
</body>
</html>

2021-10-04 07:57:21,298 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Issue with dydx API GET to v3/markets, response: 
2021-10-04 07:57:21,298 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | api.dydx.exchange used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />
<script defer src="https://api.radar.cloudflare.com/beacon.js"></script>
</head>
<body>
<div id="cf-wrapper">
<div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
<div id="cf-error-details" class="p-0">
<header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased">
<h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight">
<span data-translate="error">Error</span>
<span>1015</span>
</h1>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 698cdbe00a2165e0 &bull;</span>
<span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2021-10-04 07:57:21 UTC</span>
<h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">You are being rate limited</h2>
</header>
<section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
<div id="what-happened-section" class="w-1/2 md:w-full">
<h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>
<p>The owner of this website (api.dydx.exchange) has banned you temporarily from accessing this website.</p>
</div>
</section>
<div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
<p class="text-13">
<span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">698cdbe00a2165e0</strong></span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 167.99.199.235</span>
<span class="cf-footer-separator sm:hidden">&bull;</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
<script type="text/javascript">
  window._cf_translation = {};
  
  
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"xxobscuredx","token":"xxobscuredx","version":"2021.9.0","si":100}'></script>
</body>
</html>

2021-10-04 07:57:30,306 - 1 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

```

</p>
</details>

Let me know if you need anything more
