### ISSUE TITLE
[Hummingbot] New gateway config command

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4732]
## Why
- To make configuration process similar to our current `config` command ( to replace `gateway list-config` and `gateway update` commands) and to make it works with new Gateway ConfigManagerV2 namespace config system.

## What
- Issue the `gateway config` command without argument lists top level namespaces from `/config` Gateway API endpoint
- Supply the second positional argument to specific namespace at any level, e.g. `ethereum`, `ethereum.networks.kovan.networkID`. All configs within the namespace are displayed, e.g. `gateway config ethereum` lists
```
networks:
  mainnet:
    chainID: 1
    nodeURL: http://localhost:8501/
    nodeApiKey: xyz123zir012312340123asdfne
  kovan:
    chainID: 42
    nodeURL: https://kovan.infura.io/v3/
    nodeApiKey: xyz123zir012312340123asdfne
```
- To update a config, supply the second argument as a config namespace and supply third argument for its new value e.g. `gateway config ethereum.networks.kovan.nodeApiKey xyzNewKeyHere`. Display confirmation message if the update is successful otherwise display error message/reason for failed execution.
- All the second position argument options are autocompleted.
- <del>`-l` and `--list` arguments to list all configs in the supplied namespace, if no namespace supplied, list top level namespaces. </del>
- <del>`-h` and `--help` argument to provide help on how to use the command</del>
- Remove `gateway list-config` and `gateway update` commands

## Definition of Done
- `gateway config` is created.
- All configs are listed, and can be updated.
- `gateway list-config` and `gateway update` commands removed.
